base/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('register_otp/', views.register_two_factor, name='register_otp'),
    path('', views.login_user, name='login'),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),

    path("users/", views.CustomersList.as_view(), name="users"),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('customer_details/<int:pk>/', views.customer_details, name='customer_details'),
    path('create_account/<int:user>/<int:customer>/', views.create_account, name='create_account'),
    path('customer_accounts_list/<int:pk>/', views.list_accounts, name='list_accounts'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),

    path('account_details/<int:pk>/<int:user>/', views.account_details, name='account_details'),
    path('make_transfer/', views.prepare_transfer, name='make_transfer'),
    path('prepare_transfer/', views.prepare_transfer, name='prepare_transfer'),
    path('do_transfer/', views.do_transfer, name='do_transfer'),
    path('check_account_exists/', views.check_account_exists, name='check_account_exists'),
    path('make_loan/', views.make_loan, name='make_loan'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('search_stocks/', views.search_stocks, name='search_stocks'),
    path('search_stocks/<str:tid>', views.stock_result, name='stock_result'),

    path('money_request/', views.make_money_request, name='money_request'),
    path('delete_money_request/<int:id>', views.delete_request, name='delete_money_request'),

    path('make_recurrent_payment/', views.prepare_recurrent_payment, name='make_recurrent_payment'),
    path('customer_recurrent_payments/', views.customer_recurrent_payments, name='customer_recurrent_payments'),
    path('list_recurrent_payments/<int:customer_pk>/', views.list_recurrent_payments, name='list_recurrent_payments'),
    path('delete_recurrent_payment/<int:task_pk>/', views.delete_recurrent_payment, name='delete_recurrent_payment'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_view, name='chat'),
    path('<str:room_name>/', views.room_view, name='chat_room'),
]

base/forms.py
from django import forms
from . models import Customer, Account, Bank
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.core.exceptions import ObjectDoesNotExist


class UserForm(forms.ModelForm):
    username = forms.CharField(help_text='')
    email = forms.EmailField(max_length=50)
    first_name = forms.CharField(required=True, max_length=20, validators=[
                                 MinLengthValidator(2, 'First name must contain at least 2 characters')])
    last_name = forms.CharField(required=True, max_length=20, validators=[
                                MinLengthValidator(2, 'Last name must contain at least 2 characters')])

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean(self):
            cleaned_data = super().clean()
            email = cleaned_data.get('email')
            username = cleaned_data.get('username')

            if User.objects.filter(email=email).exclude(username=username).exists():
                msg = 'A user with that email already exists.'
                self.add_error('email', msg)           
        
            return self.cleaned_data

class CustomerForm(forms.ModelForm):
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'autocomplete': 'off','pattern':'[0-9]+', 'title':'Enter numbers Only '}))
    class Meta:
        model = Customer
        fields=['rank','phone_number']
        widgets = {
        'rank': forms.Select(attrs={'class': 'form-control'}),
    }

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields=['account_type']
        widgets = {
        'account_type': forms.Select(attrs={'class': 'form-control'})
        }

class TransferForm(forms.Form):
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    bank = forms.ModelChoiceField(label='Credit Bank', queryset=Bank.objects)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        """ credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.']) """

        # Ensure positive amount
        """ if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.']) """

        return self.cleaned_data

class TickerForm(forms.Form):
    ticker = forms.CharField(label='Enter stock symbol', max_length=5)

class MoneyRequestForm(forms.Form):
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Your Account', queryset=Customer.objects.none())
    credit_account = forms.IntegerField(label='Request Account')
    text = forms.CharField(label='Reason', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data

class RecurrentPaymentForm(forms.Form):
    name = forms.CharField(label='Name for your recurrent payment', max_length=25)
    amount  = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    bank = forms.ModelChoiceField(label='Credit Bank', queryset=Bank.objects)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)
    time_value = forms.IntegerField(label='Every', widget=forms.TextInput(attrs={'class': 'time-value'}))
    time_freq = forms.ChoiceField(
        choices=[
            ('seconds', 'Seconds'),
            ('minutes', 'Minutes'),
            ('hours', 'Hours'),
            ('days', 'Days'),
            ('months', 'Months'),
        ],
        label='',
    )

    def clean(self):
        super().clean()
        return self.cleaned_data

base/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic.list import ListView
from secrets import token_urlsafe
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.core.exceptions import PermissionDenied
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login as auth_login
from decimal import Decimal
from django.contrib.auth.models import User
import qrcode
import qrcode.image.svg
from io import BytesIO
from django_otp import devices_for_user
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp import match_token
from django.core.exceptions import ObjectDoesNotExist
from django.db import transaction
from .forms import UserForm, CustomerForm, AccountForm, TransferForm, TickerForm, MoneyRequestForm, RecurrentPaymentForm
from django.contrib.auth.decorators import login_required
from . models import Customer, Account, Transaction, MoneyRequest, Bank
from .tiingo import get_meta_data, get_price_data
import requests
from django.views.decorators.csrf import csrf_exempt
from django_celery_beat.models import PeriodicTask, IntervalSchedule
from django.utils import timezone
import json



def login_user(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('users')
        else:
            return redirect('dashboard')

    if request.method == 'GET':
        return render(request, 'base/login.html')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        otp_token = request.POST['token']
        user = authenticate(
            request=request, username=username, password=password)

        if user is not None:
            device_match = match_token(user=user, token=otp_token)
            print("DEVICE MATCH :::: ", device_match)

            if device_match is None:
                return render(request, 'base/login.html', {'error': 'Error - authentication token was wrong, or you have not registered two factor auth'})
            else:
                auth_login(request, user)
                if request.user.is_staff:
                    return HttpResponseRedirect(reverse('users'))
                else:
                    return HttpResponseRedirect(reverse('dashboard'))

        else:
            return render(request, 'base/login.html', {'error': 'Error - User not found'})

@login_required
def dashboard(request):
    assert not request.user.is_staff, 'Staff user routing customer view.'

    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'base/dashboard.html', context)


class CustomersList(LoginRequiredMixin, ListView):
    model = Customer
    context_object_name = "users"
    template_name = "base/customers_list.html"


def getCurrentBankObject(request):
    port = request.get_port()
    bank = Bank.objects.get(port=port)
    return bank
    

@login_required
def create_customer(request): # because we need to insert data in 2 tables with the same form, need to create objects for that to define what goes where
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST': # if we click submit for the form, this happens
        user_form = UserForm(request.POST)
        customer_form = CustomerForm(request.POST)
        if user_form.is_valid() and customer_form.is_valid(): # validation from forms.py and models.py
            username = user_form.cleaned_data['username']
            first_name = user_form.cleaned_data['first_name']
            last_name = user_form.cleaned_data['last_name']
            email = user_form.cleaned_data['email']
            password = token_urlsafe(16)
            rank = customer_form.cleaned_data['rank']
            phone_number = customer_form.cleaned_data['phone_number']
            bank = getCurrentBankObject(request)
            try:
                with transaction.atomic():
                    user = User.objects.create_user( # we use Model.objects.create for only inserting the data, not updating
                        username=username,           # populate user table
                        password=password,
                        email=email,
                        first_name=first_name,
                        last_name=last_name
                    )
                    Customer.objects.create( # populate customer table
                        user=user,
                        rank=rank,
                        phone_number=phone_number,
                        bank=bank
                    )
                    # return staff_customer_details(request, user.pk)
                    return redirect("users")
            except IntegrityError:
                context = {
                    'title': 'Database Error',
                    'error': 'User could not be created.'
                }
                return render(request, 'base/error.html', context)
    else: # we don't click anything yet, so just show me the forms
        user_form = UserForm()
        customer_form = CustomerForm()
    context = {
        'user_form': user_form,
        'customer_form': customer_form,
    }
    return render(request, 'base/create_customer.html', context)

@login_required
def customer_details(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk) # calls the given model and get object from that, pk tells which customer to use
    if request.method == 'GET': # thats for displaying info in the fields
        user_form = UserForm(instance=customer.user) # customer.user tells which user to access
        customer_form = CustomerForm(instance=customer) # in customer variable above we defined already which customer to access
    elif request.method == 'POST': # pass the fields to update customer info
        user_form = UserForm(request.POST, instance=customer.user) # here we need the instance to let know which user to update
        customer_form = CustomerForm(request.POST, instance=customer)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
    account_form = AccountForm() # just show me empty form for creating a new account
    context = {
        'customer': customer,
        'user_form': user_form,
        'customer_form': customer_form,
        'account_form': account_form,
    }
    return render(request, 'base/customer_details.html', context)

@login_required
def create_account(request, user, customer):
    assert request.user.is_staff, 'Customer user routing staff view.'

    if request.method == 'POST':
        account_form = AccountForm(request.POST)
        if account_form.is_valid():
            Account.objects.create(
                user=User.objects.get(pk=user), 
                account_type=account_form.cleaned_data['account_type']
                )
    return HttpResponseRedirect(reverse('customer_details', args=(customer,))) # args in the url
    # trailing comma is required for single-item tuples to disambiguate defining a tuple from an expression surrounded by parentheses
    # HttpResponseRedirect prevents data from being posted twice if a user hits the Back button

@login_required
def list_accounts(request, pk):
    assert request.user.is_staff, 'Customer user routing staff view.'

    customer = get_object_or_404(Customer, pk=pk)
    accounts = customer.accounts
    context = {
        'accounts': accounts,
    }
    return render(request, 'base/customer_accounts_list.html', context)

@login_required
def account_details(request, pk, user):
    account = get_object_or_404(Account, user=user, pk=pk)
    context = {
        'account': account
    }
    return render(request, 'base/account_details.html', context)

@login_required
def transaction_details(request, transaction):
    movements = Transaction.objects.filter(transaction=transaction)
    if not request.user.is_staff:
        if not movements.filter(account__in=request.user.customer.accounts):
            raise PermissionDenied('Customer is not part of the transaction.')
    context = {
        'movements': movements,
    }
    return render(request, 'base/transaction_details.html', context)

@login_required
def prepare_transfer(request):
    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts # a collection of data from a database. A QuerySet is built up as a list of objects.
        if form.is_valid():                                                    # queryset allows to filter and order the data.
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = form.cleaned_data['credit_account']
            credit_text = form.cleaned_data['credit_text']

            debit_bank = getCurrentBankObject(request)
            debit_bank_link = f"{debit_bank.link}:{debit_bank.port}/"
            credit_bank = Bank.objects.get(pk=form.cleaned_data['bank'].pk)
            credit_bank_link = f"{credit_bank.link}:{credit_bank.port}/"

            # Define tokens for cookies
            debit_bank_token = debit_bank.api_token
            credit_bank_token = credit_bank.api_token

            debit_account_counterparty = request.user.customer.full_name()

            if amount <= 0:
                context = {
                    'title': 'Error',
                    'error': 'Amount should be a positive number'
                }
                return render(request, 'base/error.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">BANK</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        {% if user.is_staff %}
                        <li class="nav-item"><a href="{% url 'users' %}" class="nav-link">Dashboard</a></li>
                        <li class="nav-item"><a href="{% url 'create_customer' %}" class="nav-link">Add new customer</a>
                        <li class="nav-item"><a href="{% url 'chat:chat' %}" class="nav-link">Support</a>
                        </li>
                        {% else %}
                        <li class="nav-item"><a href="{% url 'dashboard' %}" class="nav-link">Dashboard</a></li>
                        <li class="nav-item"><a href="{% url 'make_transfer' %}" class="nav-link">Make Transfer</a></li>
                        <li class="nav-item"><a href="{% url 'make_loan' %}" class="nav-link">Make Loan</a></li>
                        <li class="nav-item"><a href="{% url 'money_request' %}" class="nav-link">Request money</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Recurrent payments
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'customer_recurrent_payments' %}">Your recurrent payments</a>
                                <a class="dropdown-item" href="{% url 'make_recurrent_payment' %}">Setup Recurrent
                                    Payment</a>
                            </div>
                        </li>
                        <li class="nav-item"><a href="{% url 'search_stocks' %}" class="nav-link">Stock prices</a></li>
                        <li class="nav-item"><a href="{% url 'chat:chat' %}" class="nav-link">Support</a>
                            {% endif %}
                    </ul>
                    <a class="btn btn-danger" style="position:absolute; right:50px;"
                        href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container py-5">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@1.1.0"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>

</html>